### ISSUE TITLE
Is this library still maintained ?

### ISSUE THREAD

**Issue by apetitpa** [psliwa/image-optimizer#29]
Hello,
I need to do some image optimizations for a project and this library seems to be suited for this purpose but I wonder if it's still maintained since the last commit date one year ago.

**Comment by psliwa** [comment]
I don't use php anymore and my php related open source activity is reduced to minimum. I don't use php libraries, so I don't have motivation to maintain them actively. Nonetheless I going to maintain this library, because it is small and it doesn't need any new features. I fixed few things today, I am going to go through issues and apply futher improvements / bug fixes soon.

Soon I will release `1.1.0` version, behaviour of the library might not be 100% backward compatible with `1.0.x`.
