### ISSUE TITLE
Suggestion: add contribution guidelines

### ISSUE THREAD

**Issue by freekmurze** [psliwa/image-optimizer#40]
Right now a contributor has no way of knowing how you like changes to be PR'ed. Adding a file with contributor guidelines would help that.

Here's the one we use for our packages. https://github.com/spatie/skeleton-php/blob/master/CONTRIBUTING.md

Not saying you should use that one, but it could serve as a nice starting point for you.

**Comment by psliwa** [comment]
I don't like bureaucracy, this library is really small, number of contributions also is not impressive. Any PR is welcome, I don't require any special rules. I think such `CONTRIBUTING.md` file is rather for maintenance team instead of contributors, so if I don't see the real value, there is no need to complicate things. Even if somebody proposed messy PR with a lot of `fix` commits or bad code formatting, I am able to rebase, cleanup code etc.

**Comment by freekmurze** [comment]
Sure thing. Your library, your rules. Thanks for explaining your thoughts about this.
